CREATE TABLE PartRelation (
    parentID INTEGER UNIQUE NOT NULL,
    childID INTEGER UNIQUE NOT NULL,
    FOREIGN KEY (parentID) REFERENCES Part(ID),
    FOREIGN KEY (childID) REFERENCES Part(ID)
);

CREATE TABLE Part (
    ID INTEGER PRIMARY KEY,
    ppath TEXT UNIQUE,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE File (
    ID INTEGER PRIMARY KEY,
    fpath TEXT UNIQUE NOT NULL,
    fname TEXT NOT NULL,
    partID INTEGER,
    FOREIGN KEY (partID) REFERENCES Part(ID)
);