CREATE TABLE Strategy (
    ID INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE Part (
    ID INTEGER PRIMARY KEY,
    depth INTEGER PRIMARY KEY,
    parent INTEGER PRIMARY KEY,
    strategy INTEGER PRIMARY KEY,
    FOREIGN KEY (parent) REFERENCES Part(ID)
    FOREIGN KEY (strategy) REFERENCES Strategy(ID)
);

CREATE TABLE File (
    ID INTEGER PRIMARY KEY,
    fpath TEXT NOT NULL,
    fname TEXT NOT NULL,
    partID INTEGER,
    FOREIGN KEY (partID) REFERENCES Part(ID)
);